language: c
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - tree
before_install:
    - export TEST_PREFIX="$(pwd)/test_prefix"
    - test "${TRAVIS_OS_NAME}" = "osx" && brew update; true
    - test "${TRAVIS_OS_NAME}" = "osx" && brew install tree; true
    - test "${TRAVIS_OS_NAME}" = "osx" && test "${CC}" = "gcc" && export CC="gcc-4.9"; true
script:
    - make CC="${CC}" PREFIX="${TEST_PREFIX}"
    - make CC="${CC}" PREFIX="${TEST_PREFIX}" install
    - make clean
    - tree "${TEST_PREFIX}"
    - rm -r "${TEST_PREFIX}"
