language: c
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get install tree
script:
    - export CC="$CC" TEST_PREFIX="`pwd/test_prefix`"
    - make CC="$CC" PREFIX="$TEST_PREFIX"
    - make CC="$CC" PREFIX="$TEST_PREFIX" install
    - tree "$TEST_PREFIX"
    - rm -r "$TEST_PREFIX"
    - make clean
